
[AtCoder]
  ContestID = "abc143"
  ContestURL = "https://atcoder.jp/contests/abc143"
  TaskID = "abc143_b"
  TaskName = "B - TAKOYAKI FESTIVAL 2019"
  TaskURL = "https://atcoder.jp/contests/abc143/tasks/abc143_b"

[Environment]
  BuildCmd = ""
  BuildCmdOnDocker = ""
  CleanCmd = ""
  Cmd = "python3 -B main.py"
  CmdOnDocker = "python -B main.py"
  DockerImage = "docker.io/sachaos/atcoder-python3:latest"
  Key = "python3"
  Language = "Python3 (3.4.3)"
  LanguageCode = "3023"
  Note = ""
  SrcName = "main.py"
  Template = "internal/python3/main.py"
