
[AtCoder]
  ContestID = "abc145"
  ContestURL = "https://atcoder.jp/contests/abc145"
  TaskID = "abc145_b"
  TaskName = "B - Echo"
  TaskURL = "https://atcoder.jp/contests/abc145/tasks/abc145_b"

[Environment]
  BuildCmd = ""
  BuildCmdOnDocker = ""
  CleanCmd = ""
  Cmd = "python3 -B main.py"
  CmdOnDocker = "python -B main.py"
  DockerImage = "docker.io/sachaos/atcoder-python3:latest"
  Key = "python3"
  Language = "Python3 (3.4.3)"
  LanguageCode = "3023"
  Note = ""
  SrcName = "main.py"
  Template = "internal/python3/main.py"
