
[AtCoder]
  ContestID = "abc144"
  ContestURL = "https://atcoder.jp/contests/abc144"
  TaskID = "abc144_d"
  TaskName = "D - Water Bottle"
  TaskURL = "https://atcoder.jp/contests/abc144/tasks/abc144_d"

[Environment]
  BuildCmd = ""
  BuildCmdOnDocker = ""
  CleanCmd = ""
  Cmd = "python3 -B main.py"
  CmdOnDocker = "python -B main.py"
  DockerImage = "docker.io/sachaos/atcoder-python3:latest"
  Key = "python3"
  Language = "Python3 (3.4.3)"
  LanguageCode = "3023"
  Note = ""
  SrcName = "main.py"
  Template = "internal/python3/main.py"
